@file:UseSerializers(InstantSerializer::class, UUIDSerializer::class)

package me.colinwatson.beerdebt.engine

import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import kotlinx.serialization.json.Json
import java.time.Instant
import java.util.UUID
import kotlin.math.abs
import kotlin.test.Test
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * The cross-platform contract. cases.json is generated by the Swift engine
 * (beer-debt-ios/scripts/fixtures.sh); every case must replay to the same
 * numbers here. Copy the file over whenever the iOS engine changes.
 */
class FixtureTest {
    @Serializable
    private data class Fixtures(val version: Int, val tolerance: Double, val note: String, val cases: List<Case>)

    @Serializable
    private data class Case(val name: String, val now: Instant, val ledger: Ledger, val expected: Expected)

    @Serializable
    private data class Expected(
        val balance: ExpectedBalance,
        val beers: List<ExpectedBeer>,
        val runs: List<ExpectedRun>,
        val nextInterestAt: Instant? = null,
        val creditExpiringThisWeekMiles: Double,
    )

    @Serializable
    private data class ExpectedBalance(
        val state: String, val debtMiles: Double, val principalMiles: Double,
        val interestMiles: Double, val creditMiles: Double, val creditBeers: Double,
    )

    @Serializable
    private data class ExpectedBeer(
        val id: UUID, val number: Int, val createdAt: Instant, val costMiles: Double, val coveredByCreditMiles: Double,
        val principalMiles: Double, val interestAccruedMiles: Double, val paidMiles: Double,
        val principalRemainingMiles: Double, val interestRemainingMiles: Double, val writtenOffMiles: Double,
        val paidAt: Instant? = null, val nextInterestAt: Instant? = null,
    )

    @Serializable
    private data class ExpectedRun(
        val id: UUID, val debtPaidMiles: Double, val creditEarnedMiles: Double, val discardedMiles: Double, val ignored: Boolean,
    )

    private val json = Json { ignoreUnknownKeys = true }

    @Test
    fun `every Swift fixture replays to the same numbers`() {
        val text = javaClass.getResource("/cases.json")?.readText() ?: fail("cases.json missing from test resources")
        val fixtures = json.decodeFromString<Fixtures>(text)
        assertTrue(fixtures.cases.size >= 60, "expected the full fixture set, got ${fixtures.cases.size}")

        val failures = fixtures.cases.mapNotNull { case ->
            runCatching { check(case, fixtures.tolerance) }.exceptionOrNull()?.let { "• ${case.name}: ${it.message}" }
        }
        assertTrue(failures.isEmpty(), "${failures.size} of ${fixtures.cases.size} fixtures failed:\n" + failures.joinToString("\n"))
        println("✓ ${fixtures.cases.size} Swift fixtures reproduced")
    }

    private fun check(case: Case, tol: Double) {
        val report = BalanceEngine.report(case.ledger, case.now)
        val e = case.expected

        fun near(label: String, actual: Double, expected: Double) {
            if (abs(actual - expected) > tol) throw AssertionError("$label: got $actual, expected $expected")
        }
        fun same(label: String, actual: Any?, expected: Any?) {
            if (actual != expected) throw AssertionError("$label: got $actual, expected $expected")
        }

        same("balance.state", report.balance.state.name.lowercase(), e.balance.state)
        near("balance.debtMiles", report.balance.debtMiles, e.balance.debtMiles)
        near("balance.principalMiles", report.balance.principalMiles, e.balance.principalMiles)
        near("balance.interestMiles", report.balance.interestMiles, e.balance.interestMiles)
        near("balance.creditMiles", report.balance.creditMiles, e.balance.creditMiles)
        near("balance.creditBeers", report.balance.creditBeers, e.balance.creditBeers)
        same("nextInterestAt", report.nextInterestAt, e.nextInterestAt)
        near("creditExpiringThisWeekMiles", report.creditExpiringThisWeekMiles, e.creditExpiringThisWeekMiles)

        same("beers.count", report.beers.size, e.beers.size)
        report.beers.zip(e.beers).forEach { (a, x) ->
            val tag = "beer #${x.number}"
            same("$tag id", a.id, x.id); same("$tag number", a.number, x.number); same("$tag createdAt", a.createdAt, x.createdAt)
            near("$tag cost", a.costMiles, x.costMiles); near("$tag coveredByCredit", a.coveredByCreditMiles, x.coveredByCreditMiles)
            near("$tag principal", a.principalMiles, x.principalMiles); near("$tag interestAccrued", a.interestAccruedMiles, x.interestAccruedMiles)
            near("$tag paid", a.paidMiles, x.paidMiles); near("$tag principalRemaining", a.principalRemainingMiles, x.principalRemainingMiles)
            near("$tag interestRemaining", a.interestRemainingMiles, x.interestRemainingMiles); near("$tag writtenOff", a.writtenOffMiles, x.writtenOffMiles)
            same("$tag paidAt", a.paidAt, x.paidAt); same("$tag nextInterestAt", a.nextInterestAt, x.nextInterestAt)
        }
        same("runs.count", report.runs.size, e.runs.size)
        report.runs.zip(e.runs).forEach { (a, x) ->
            val tag = "run ${x.id}"
            same("$tag id", a.id, x.id); near("$tag debtPaid", a.debtPaidMiles, x.debtPaidMiles)
            near("$tag creditEarned", a.creditEarnedMiles, x.creditEarnedMiles); near("$tag discarded", a.discardedMiles, x.discardedMiles)
            same("$tag ignored", a.ignored, x.ignored)
        }
    }
}
